---
title: "Data processing"
author: "Jamie Cummins & Ian Hussey"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

```

```{r}

library(tidyverse)

# raw_trial_level_df <- read.delim("../../data/raw/impraw.txt") 
# raw_sessions_df <- read.delim("../../data/raw/allds.txt")
# 
# write_rds(raw_trial_level_df, "../../data/raw/impraw.rds", compress = "gz")
# write_rds(raw_sessions_df, "../../data/raw/allds.rds", compress = "gz")

raw_trial_level_df <- read_rds("../../data/raw/impraw.rds")
raw_sessions_df <- read_rds("../../data/raw/allds.rds")

```

# screen and identify the completed sessions and their corresponding measures

```{r}

completed_sessions_df <- raw_sessions_df |>
  select(User_ID, SESSION_ID, 
         contains(c("Race", "Pltc", "Self")), 
         -contains(c("21", "22", "31", "32", "33", 
                     "RT", "cgat"))) |>
  mutate(across(everything(),
                as.character)) |>
  pivot_longer(cols = -contains(c("ID")),
               names_to = "scale",
               values_to = "score") %>%
  filter(!is.na(score),
         scale != "race") |>
  separate(scale, 
           c("measure", "domain"),
           "(?!^)(?=[[:upper:]])") |>
  select(User_ID, SESSION_ID)

```

# tidy the trial-level data and include only those completed cases

```{r}

# write_rds(raw_trial_level_df, "../../data/intermediate/raw_trial_level_df.rds")
# write_rds(completed_sessions_df, "../../data/intermediate/completed_sessions_df.rds")

# raw_trial_level_df <- read_rds("../../data/intermediate/raw_trial_level_df.rds")
# completed_sessions_df <- read_rds("../../data/intermediate/completed_sessions_df.rds")

temp <- distinct(completed_sessions_df, SESSION_ID, .keep_all = TRUE)

trial_level_tasks_combined <- raw_trial_level_df |>
  mutate(across(everything(), as.character)) |>
  # remove sessions with no complete implicit measures
  semi_join(completed_sessions_df, by = "SESSION_ID") |>
  # join with completed_sessions_df to pull in User_ID
  left_join(distinct(completed_sessions_df, SESSION_ID, .keep_all = TRUE), by = "SESSION_ID")

# write_rds(trial_level_tasks_combined, "../../data/intermediate/trial_level_tasks_combined.rds")
# trial_level_tasks_combined <- read_rds("../../data/intermediate/trial_level_tasks_combined.rds")

trial_level_tasks_labelled_df <- trial_level_tasks_combined |>
  mutate(measure_firstblock = case_when(TASK_NAME_S %in% c("BBlkBad", "BWhtGood",
                                                           "BRepBad", "BDemGood",
                                                           "BOtrBad", "BSlfGood") ~ "biat_con",
                                        TASK_NAME_S %in% c("BBlkGood", "BWhtBad",
                                                           "BRepGood", "BDemBad",
                                                           "BOtrGood", "BSlfBad") ~ "biat_incon",
                                        TASK_NAME_S %in% c("GBlkBad", "GWhtGood",
                                                           "GRepBad", "GDemGood",
                                                           "GOtrBad", "GSlfGood") ~ "gnat_con",
                                        TASK_NAME_S %in% c("GBlkGood", "GWhtBad",
                                                           "GRepGood", "GDemBad",
                                                           "GOtrGood", "GSlfBad") ~ "gnat_incon",
                                        TASK_NAME_S %in% c("eppltc", 
                                                           "eprace", "epself") ~ "ept",
                                        TASK_NAME_S %in% c("amppltc", 
                                                           "amprace", "ampself") ~ "amp",
                                        TASK_NAME_S %in% c("iwhtgood", 
                                                           "iDemGood", "iSlfGood") ~ "iat_con",
                                        TASK_NAME_S %in% c("iwhtbad", 
                                                           "iRepGood", "iSlfBad") ~ "iat_incon",
                                        TASK_NAME_S %in% c("scbdblk", "scbdotr",
                                                           "scbdrep", "scgddem",
                                                           "scgdslf", "scgdwht") ~ "siat_con",
                                        TASK_NAME_S %in% c("scgdblk", "scgdotr",
                                                           "scgdrep", "scbddem",
                                                           "scbdslf", "scbdwht") ~ "siat_incon",
                                        TASK_NAME_S %in% c("spdpltc", "spdrace",
                                                           "spdself") ~ "speededresponse",
                                        TRUE ~ "irrelevant")) |>
  mutate(domain = case_when(str_detect(TASK_NAME_S, "Blk|Wht|blk|wht|race") ~ "race",
                            str_detect(TASK_NAME_S, "Slf|Otr|slf|otr|self") ~ "self",
                            str_detect(TASK_NAME_S, "Dem|Rep|dem|rep|pltc") ~ "politics",
                            TRUE ~ "irrelevant")) |>
  filter(domain != "irrelevant",
         measure_firstblock != "irrelevant") |>
  separate(measure_firstblock,
           into = c("measure", "first_block"),
           sep = "_")

# write_rds(trial_level_tasks_labelled_df, "../../data/intermediate/trial_level_tasks_labelled_df.rds")
# trial_level_tasks_labelled_df <- read_rds("../../data/intermediate/trial_level_tasks_labelled_df.rds")

```

# score measures

```{r}

block_consistent_terms <- "White People/Good|Self/Good|Democrats/Good|Good Words/White|Bad Words/Black|Good Words/Democrats|Bad Words/Republicans|Good Words/Self|Bad Words/Others"
block_inconsistent_terms <- "Black People/Good|Others/Good|Republicans/Good|Good Words/Black|Bad Words/White|Good Words/Republicans|Bad Words/Democrats|Good Words/Others|Bad Words/Self"
trial_consistent_terms <- "mtmmgore|mtmmkry|mtmmclnt|mtmmobm|mtmmbclnt|mtmmhclnt|Mine|Me|Myself|Self|\\[I\\]|epwm|epwf|mtmmwf|mtmmwm"
trial_inconsistent_terms <- "mtmmrgn|mtmmbsh|mtmmgln|mtmmcnd|They|Them|Their|Others|epbm|epbf|mtmmbf|mtmmbm"

critical_trials_df <- trial_level_tasks_labelled_df |>
  
  # keep only relevant blocks/trials
  filter(
    (measure == "iat" & BLOCK_NUMBER %in% c("2", "3", "5", "6"))
    |
    (measure == "biat" & BLOCK_NUMBER %in% c(1:8) & TRIAL_NUMBER %in% c(4:19))
    |
    (measure == "amp" & BLOCK_NUMBER %in% c(1:2) & str_detect(TRIAL_NAME_S, "[XXXXXX]|Grey", negate = TRUE))
    |
    (measure == "gnat" & BLOCK_NUMBER %in% c(1:8))
    |
    (measure == "ept" & BLOCK_NUMBER %in% c(1:3))
    |
    (measure == "siat")) |>
  mutate(trial_consistency = case_when(
    measure %in% c("iat", "biat", "gnat") & 
      str_detect(BLOCK_PAIRING_DEFINITION_S, 
                 block_consistent_terms) ~ "consistent",
    measure %in% c("iat", "biat", "gnat") & 
      str_detect(BLOCK_PAIRING_DEFINITION_S, 
                 block_inconsistent_terms) ~ "inconsistent",
    measure == "amp" & str_detect(TRIAL_NAME_S, 
                                  trial_consistent_terms) ~ "consistent",
    measure == "amp" & str_detect(TRIAL_NAME_S, 
                                  trial_inconsistent_terms) ~ "inconsistent",
    measure == "siat" & 
      str_detect(BLOCK_PAIRING_DEFINITION_S, 
                 block_consistent_terms) ~ "consistent",
    measure == "siat" & 
      str_detect(BLOCK_PAIRING_DEFINITION_S, 
                 block_inconsistent_terms) ~ "inconsistent",
    measure == "ept" & 
      TRIAL_RESPONSE_S == "Good" & 
      str_detect(TRIAL_NAME_S, 
                 trial_consistent_terms) ~ "consistent",
    measure == "ept" & 
      TRIAL_RESPONSE_S == "Bad" & 
      str_detect(TRIAL_NAME_S,
                 trial_inconsistent_terms) ~ "consistent",
    measure == "ept" & 
      TRIAL_RESPONSE_S == "Good" & 
      str_detect(TRIAL_NAME_S, 
                 trial_inconsistent_terms) ~ "inconsistent",
    measure == "ept" & 
      TRIAL_RESPONSE_S == "Bad" & 
      str_detect(TRIAL_NAME_S, 
                 trial_consistent_terms) ~ "inconsistent"),
    TRIAL_ERROR = as.numeric(TRIAL_ERROR),
    TRIAL_LATENCY = as.numeric(TRIAL_LATENCY),
    score = case_when(measure %in% c("iat", "biat", "siat", "gnat", "ept") ~ TRIAL_LATENCY,
                      measure %in% c("amp") ~ TRIAL_ERROR))

# write_rds(critical_trials_df, "../../data/intermediate/critical_trials_df.rds")
# critical_trials_df <- read_rds("../../data/intermediate/critical_trials_df.rds")

```

# Self reports

```{r}

data_self_report <- trial_level_tasks_labelled_df |>
  filter(measure == "speededresponse") |>
  select(user_id = User_ID, 
         session_id = SESSION_ID,
         attempt = ATTEMPT, 
         domain, 
         block_number = BLOCK_NUMBER, 
         block_name = BLOCK_NAME_S,
         block_type = BLOCK_PAIRING_DEFINITION_S,
         task_number = TASK_NUMBER,
         trial_name = TRIAL_NAME_S,
         response = TRIAL_RESPONSE_S) |>
  filter(block_type != "Example" & 
           !str_detect(trial_name, "Targets")) |>
  mutate(trial_name_original = trial_name,
         trial_name = sub("\\[", "", trial_name),
         trial_name = sub("*\\].*", "", trial_name),
         response = ifelse(response == 999, NA, as.numeric(response))) 

data_self_report_summary <- data_self_report |>
  group_by(session_id, domain, trial_name) |>
  summarize(mean_response = mean(response, na.rm = TRUE)) |>
  ungroup() |>
  mutate(mean_response = ifelse(is.nan(mean_response), NA, mean_response)) |>
  mutate(category = case_when(trial_name %in% c("White People", "Self", "Democrats") ~ "evaluation_category_1",
                              trial_name %in% c("Black People", "Others", "Republicans") ~ "evaluation_category_2")) |>
  select(-trial_name) |>
  drop_na(mean_response) |>
  pivot_wider(names_from = category,
              values_from = mean_response) |>
  filter(!is.na(evaluation_category_1) & !is.na(evaluation_category_2)) |>
  mutate(evaluation_difference = evaluation_category_2 - evaluation_category_1,
         evaluation_difference_absolute = abs(evaluation_difference))

# write_rds(data_self_report_summary, "../../data/processed/data_self_report_summary.rds")
# data_self_report_summary <- read_rds("../../data/processed/data_self_report_summary.rds")

```

# apply exclusions

## at session level

Exclusions applied same as those from Bar-Anan & Nosek, 2014

```{r}

participants_after_session_level_exclusions <- critical_trials_df |>
  mutate(rt_under_300 = case_when(TRIAL_LATENCY < 300 ~ 1,
                                   TRUE ~ 0)) |>
  group_by(User_ID, SESSION_ID, measure, domain) |>
  summarise(mean_rts_under_300 = mean(rt_under_300),
            mean_errors = mean(TRIAL_ERROR)) |>
  ungroup() |>
  filter(
    (measure %in% c("iat", "biat", "siat", "gnat") & mean_rts_under_300 < .1) 
    |
    (measure %in% c("ept") & mean_errors < .4) # errors are coded as 1
    | 
    (measure %in% c("amp") & (mean_errors < .95 & mean_errors > .05))
  ) |>
  select(User_ID, SESSION_ID, measure, domain)
  
participants_after_session_level_exclusions |>
  count(measure, domain)

```

## at trial level

Exclusions applied same as those from Bar-Anan & Nosek, 2014

```{r}

all_exclusions_applied_df <- critical_trials_df |>
  semi_join(participants_after_session_level_exclusions) |>
  filter(
    (measure %in% c("iat", "biat", "siat") & (TRIAL_LATENCY > 400 & TRIAL_LATENCY < 10000)) 
    |
    (measure %in% c("gnat") & (TRIAL_LATENCY > 400 & TRIAL_LATENCY < 1200) & (TRIAL_ERROR %in% c(0, 3)))
    |
    (measure %in% c("ept") & (1500 >= TRIAL_LATENCY))
    |
    (measure %in% c("amp"))
  )

write_rds(all_exclusions_applied_df, "../../data/processed/data_trials_for_scoring.rds", compress = "gz")
# all_exclusions_applied_df <- read_rds("../../data/processed/data_trials_for_scoring.rds")

```

# A scores

```{r}

# Fast calculation of the A statistic - code from Ruscio (2008) supplementary materials
A_score <- function(data, i) {
  data_with_indexes <- data[i,] # boot function requires data and index
  x  <- na.omit(data_with_indexes$score[data_with_indexes$block_type == "inconsistent"])
  y  <- na.omit(data_with_indexes$score[data_with_indexes$block_type == "consistent"])
  nx <- length(x)
  ny <- length(y)
  rx <- sum(rank(c(x, y))[1:nx])
  A <- (rx / nx - (nx + 1) / 2) / ny
  return(A)
}

# A scores 
data_for_A_scores <- all_exclusions_applied_df |>
  rename(block_type = trial_consistency,
         user_id    = User_ID, 
         session_id = SESSION_ID) |>
  mutate(block_type = as.character(block_type),
         session_id = as.factor(session_id)) |>
  
  # ensure a sufficient number of observations per person per measure per trial type
  group_by(session_id, measure, domain, block_type) |>
  filter(n() >= 10) |>
  
  # remove those who do not have sufficient observations for both trials per measure
  group_by(session_id, domain, measure) |>
  filter(n_distinct(block_type) == 2)

A_scores <- data_for_A_scores |>
  # do bootstrapping scores
  group_by(session_id, measure, domain) |>
  do(A_score(data = .)) |>
  ungroup()

# save to disk
write_rds(A_scores, "../../data/processed/data_processed_point_estimates.rds")

```



