---
title: "Comparing 6 implicit measures' suitability for individual use"
subtitle: "Robustness tests using Beta regression models instead of empirical logit models"
author: "Ian Hussey"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    code_folding: hide
    highlight: haddock
    theme: flatly
    toc: yes
    toc_float: yes
---

```{r, include=FALSE}
knitr::opts_chunk$set(message=FALSE,
                      warning=FALSE,
                      cache.lazy=FALSE)
```

```{r}

# dependencies
library(tidyverse)
library(knitr)
library(kableExtra)
library(boot)
library(parallel)
library(mdthemes)
library(sjPlot)
library(emmeans)
library(ggstance)
library(janitor)
library(performance)
library(brms)

# create necessary directories
dir.create("../../data/results")
dir.create("plots")
dir.create("models")

# set seed for reproducibility
set.seed(42)

# options
options(knitr.table.format = "html") # necessary configuration of tables

# disable scientific notation
options(scipen = 999)


# function to round all numeric vars in a data frame
round_df <- function(df, n_digits = 3) {
  require(janitor)
  df %>% mutate_if(is.numeric, janitor::round_half_up, digits = n_digits)
}

```

# Load scored data

```{r}

data_processed <- read_rds("../../data/processed/data_processed_testing.rds")

```

# RQ1. Proportion of indiviudal scores that are detectably different from zero

```{r fig.height=4, fig.width=6}

# wrangle data
data_diff_zero <-
  data_processed %>%
  mutate(domain = as.factor(domain)) %>%
  group_by(domain, measure) %>%
  summarize(proportion_diff_zero = mean(sig, na.rm = TRUE),
            variance = plotrix::std.error(sig, na.rm = TRUE)^2,
            .groups = "drop") %>%
  mutate(variance = ifelse(variance == 0, 0.001, variance))

# fit model
beta_model_diff_zero <- bf(
  proportion_diff_zero ~ 1 + measure + (1 | domain),
  phi ~ 1 + measure + (1 | domain),
  family = Beta()
)

fit_beta_diff_zero <- 
  brm(formula  = beta_model_diff_zero,
      data     = data_diff_zero,
      cores    = 4,
      iter     = 5000,
      control = list(adapt_delta = 0.95),
      file     = "models/fit_beta_diff_zero")

results_beta_diff_zero <- conditional_effects(fit_beta_diff_zero)$measure |>
  select(measure, estimate = estimate__, ci_lower = lower__, ci_upper = upper__) |>
  mutate(measure = fct_rev(fct_relevel(measure, "IAT", "Brief IAT", "SC-IAT", "AMP", "GNAT", "EPT")))

# # alt method:
# results_beta_diff_zero <- 
#   fit_beta_diff_zero |>
#   emmeans("measure") |>
#   summary(point.est = mean) |>
#   as.tibble() |>
#   dplyr::mutate(estimate = boot::inv.logit(emmean),
#                 ci_lower = boot::inv.logit(lower.HPD),
#                 ci_upper = boot::inv.logit(upper.HPD)) |>
#   mutate(measure = fct_rev(fct_relevel(measure, "IAT", "Brief IAT", "SC-IAT", "AMP", "GNAT", "EPT")))

ggplot(results_beta_diff_zero, aes(estimate, measure)) +
  geom_linerange(aes(xmin = ci_lower, xmax = ci_upper)) +
  geom_point(size = 2.5, shape = 15) +
  scale_x_continuous(breaks = c(0, .25, .5, .75, 1), 
                     labels = c("0.00", "0.25", "0.50", "0.75", "1.00"),
                     limits = c(0,1)) +
  labs(x = "Proportion of participants<br/>with non-zero effects",
       y = "") +
  mdthemes::md_theme_linedraw() 

results_beta_diff_zero |>
  round_df(2) |>
  kable() |>
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = FALSE)

```

# RQ2. Probability that differences can be detected between two participants' scores

```{r fig.height=4, fig.width=6}

# get data
data_discriminability <- read_csv("../../data/results/data_discriminability.csv") |>
  mutate(measure = fct_relevel(measure, "IAT", "Brief IAT", "SC-IAT", "AMP", "GNAT", "EPT"))

# fit model
beta_model_disciminability <- bf(
  proportion_discriminable ~ 1 + measure + (1 | domain),
  phi ~ 1 + measure + (1 | domain),
  family = Beta()
)

fit_beta_disciminability <- 
  brm(formula  = beta_model_disciminability,
      data     = data_discriminability,
      cores    = 4,
      iter     = 5000,
      control = list(adapt_delta = 0.95),
      file     = "models/fit_beta_disciminability")

results_beta_disciminability <- conditional_effects(fit_beta_disciminability)$measure |>
  select(measure, estimate = estimate__, ci_lower = lower__, ci_upper = upper__) |>
  mutate(measure = fct_rev(fct_relevel(measure, "IAT", "Brief IAT", "SC-IAT", "AMP", "GNAT", "EPT")))

ggplot(results_beta_disciminability, aes(estimate, measure)) +
  geom_linerange(aes(xmin = ci_lower, xmax = ci_upper)) +
  geom_point(size = 2.5, shape = 15) +
  scale_x_continuous(breaks = c(0, .25, .5, .75, 1), 
                     labels = c("0.00", "0.25", "0.50", "0.75", "1.00"),
                     limits = c(0,1)) +
  labs(x = "Probability that differences can be detected<br/>between two participants' scores<br/>",
       y = "") +
  mdthemes::md_theme_linedraw() 

results_beta_disciminability |>
  round_df(2) |>
  kable() |>
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = FALSE)

```

# RQ3. Proportion of observed range of 95% CI widths covered by individual participants' 95% CIs

```{r fig.height=4, fig.width=6}

# wrangle data
observed_range_estimates <- data_processed %>%
  group_by(measure, domain) %>%
  dplyr::summarize(min = min(ci_lower, na.rm = TRUE),
                   max = max(ci_upper, na.rm = TRUE),
                   .groups = "drop") %>%
  mutate(range = max - min)

# calculate CI / range
data_ci_width_proportions <- data_processed %>%
  # join this data into the original data
  full_join(observed_range_estimates, by = c("measure", "domain")) %>%
  # calculate ci width as a proportion of observed range
  mutate(ci_width_proportion = ci_width / range,
         domain = as.factor(domain),
         measure = fct_relevel(measure, "IAT", "Brief IAT", "SC-IAT", "AMP", "GNAT", "EPT")) %>%
  group_by(domain, measure) %>%
  summarize(ci_width_proportion_mean = mean(ci_width_proportion, na.rm = TRUE),
            variance = plotrix::std.error(ci_width_proportion)^2) %>%
  ungroup()

# fit model
beta_model_ci_width_proportions <- bf(
  ci_width_proportion_mean ~ 1 + measure + (1 | domain),
  phi ~ 1 + measure + (1 | domain),
  family = Beta()
)

fit_beta_ci_width_proportions <- 
  brm(formula  = beta_model_ci_width_proportions,
      data     = data_ci_width_proportions,
      cores    = 4,
      iter     = 5000,
      control = list(adapt_delta = 0.95),
      file     = "models/fit_beta_ci_width_proportions")

results_beta_ci_width_proportions <- conditional_effects(fit_beta_ci_width_proportions)$measure |>
  select(measure, estimate = estimate__, ci_lower = lower__, ci_upper = upper__) |>
  mutate(measure = fct_rev(fct_relevel(measure, "IAT", "Brief IAT", "SC-IAT", "AMP", "GNAT", "EPT")))

ggplot(results_beta_ci_width_proportions, aes(estimate, measure)) +
  geom_linerange(aes(xmin = ci_lower, xmax = ci_upper)) +
  geom_point(size = 2.5, shape = 15) +
  scale_x_continuous(breaks = c(0, .25, .5, .75, 1), 
                     labels = c("0.00", "0.25", "0.50", "0.75", "1.00"),
                     limits = c(0,1)) +
  labs(x = "Proportion of observed range covered <br/>by individual participants' 95% CIs",
       y = "") +
  mdthemes::md_theme_linedraw() 

results_beta_ci_width_proportions |>
  round_df(2) |>
  kable() |>
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = FALSE)

```

# Session info

```{r}

sessionInfo()

```


